"""Initial migration: create users, transactions, budgets, and payments tables

Revision ID: 0e8b1767a4ec
Revises: 
Create Date: 2025-11-15 08:20:29.171383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e8b1767a4ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('major', sa.String(), nullable=True),
    sa.Column('class_year', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', 'VENDOR', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=True)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('limit_amount', sa.Float(), nullable=False),
    sa.Column('period', sa.Enum('WEEKLY', 'MONTHLY', name='budgetperiod'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_category'), 'budgets', ['category'], unique=False)
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('EVENT', 'CLUB', 'DINING', 'PRINTING', 'SERVICE', 'OTHER', name='paymenttype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('DINING', 'BOOKS', 'TRANSPORTATION', 'ENTERTAINMENT', 'SERVICES', 'OTHER', name='transactioncategory'), nullable=False),
    sa.Column('merchant', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('payment_method', sa.Enum('CARD', 'CASH', 'MOBILE', 'CAMPUS_CARD', name='paymentmethod'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garmin_health_sleeps',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('calendar_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('summary_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time_offset_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_nap_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unmeasurable_sleep_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deep_sleep_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('light_sleep_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rem_sleep_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('awake_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deep_sleep_start_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deep_sleep_end_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('light_sleep_start_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('light_sleep_end_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('awake_start_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('awake_end_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('validation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('overall_sleep_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overall_sleep_qualifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_duration_qualifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stress_qualifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('awake_qualifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rem_percentage_qualifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reslessness_qualifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('light_percentage_qualifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deep_percentage_qualifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_a84754c18c1e6bd5e7b61f81dc5')
    )
    op.create_table('trailforks_hike',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('trail_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('elevation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ft_difficulty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ft_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ft_votes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ft_parking', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ft_likely_parking', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ft_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ft_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ft_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('label', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_751d2b1c2de44dec54eae347e3c')
    )
    op.create_table('activity_baseline',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('activity_subtype', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('activity_baseline', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('activity_goal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_valid', sa.VARCHAR(), server_default=sa.text("'VALID'::character varying"), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_e3317f523a244f849daa21c8e0f'),
    sa.PrimaryKeyConstraint('id', name='PK_c630396f3e20a055c87451bb021')
    )
    op.create_table('activity_goal',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('activity_goal', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_valid', sa.VARCHAR(), server_default=sa.text("'VALID'::character varying"), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_854d60a8b51ac8af0b2c024c696'),
    sa.PrimaryKeyConstraint('id', name='PK_ffba2360d2e004af483d51f8741')
    )
    op.create_table('notification',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sender_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sender_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sender_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('redirect_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_928b7aa1754e08e1ed7052cb9d8'),
    sa.PrimaryKeyConstraint('id', name='PK_705b6c7cdf9b2c2ff7ac7872cb7')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('picture_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'CREATED'::character varying"), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_cace4a159ff9f2512dd42373760'),
    sa.UniqueConstraint('email', name='UQ_e12875dfb3b1d92d7d7c5377e22'),
    postgresql_ignore_search_path=False
    )
    op.create_table('analytics',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('data_points', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_478656673247334d8cea26a2c12'),
    sa.PrimaryKeyConstraint('id', name='PK_3c96dcbf1e4c57ea9e0c3144bff')
    )
    op.create_table('garmin_deregistrations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_c5a0a53f7b80f32ae28d523651e')
    )
    op.create_table('shared_list',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_c1f6cad442dac78fe875d3893db'),
    postgresql_ignore_search_path=False
    )
    op.create_table('garmin_health_dailies',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('calendar_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active_kilocalories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bmr_kilocalories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('steps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pushes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distance_in_meters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('push_distance_in_meters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_time_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time_offset_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('moderate_intensity_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vigorous_intensity_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('floors_climbed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_heart_rate_in_beats_per_minute', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_heart_rate_in_beats_per_minute', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_heart_rate_in_beats_per_minute', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_stress_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_stress_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stress_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rest_stress_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity_stress_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('low_stress_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medium_stress_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('high_stress_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stress_qualifer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('steps_goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pushes_goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intensity_duration_goal_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('floors_climbed_goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_0c0c99251f2569297b2d2341f3b')
    )
    op.create_table('typeorm_migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_bb2f075707dd300ba86d0208923')
    )
    op.create_table('bookmark',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_8f1a143c6ba8bba0e2a4f41e0d0'),
    sa.PrimaryKeyConstraint('id', name='PK_b7fbf4a865ba38a590bb9239814')
    )
    op.create_table('mood_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('mood_level', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('energy_level', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_2c1bc643bcacdf8b60eeb43ecbd'),
    sa.PrimaryKeyConstraint('id', name='PK_9f332fef75c6259bf26f25ef90c')
    )
    op.create_table('activity_type',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_fc087d79002cef578e27dd9fdab')
    )
    op.create_table('profile',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('preferred_activities', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('personal_goals', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_d752442f45f258a8bdefeebb2f2'),
    sa.PrimaryKeyConstraint('id', name='PK_3dd8bfc97e4a77c70971591bdcb')
    )
    op.create_table('authorization_code',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('key_public', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('key_private', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_e259cc0926bf29f2d053ba4bae5'),
    sa.PrimaryKeyConstraint('id', name='PK_586233caf7e281dc24aaedd1335')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='FK_56587784c114247817dbabfb4a2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_d30e91e4fd0166444f2a5319046'),
    sa.PrimaryKeyConstraint('id', name='PK_17cb51984a6627ef2ce7370e23c')
    )
    op.create_table('garmin_activity_details',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('activity_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('activity_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time_in_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time_offset_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('average_heart_rate_in_beats_per_minute', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_run_cadence_in_steps_per_minute', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_speed_in_meters_per_second', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_pace_in_minutes_per_kilometer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('active_kilocalories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('distance_in_meters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_heart_rate_in_beats_per_minute', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_pace_in_minutes_per_kilometer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_run_cadence_in_steps_per_minute', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_speed_in_meters_per_second', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('steps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_elevation_gain_in_meters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_7bdbb7b7666c005dd3f5c7e6e48')
    )
    op.create_table('garmin_oauth',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('garmin_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_access_secret', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_176d6811b96319e1b980ee279b4')
    )
    op.create_table('preferred_activity',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_valid', sa.VARCHAR(), server_default=sa.text("'VALID'::character varying"), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_796c753ab40386b6eaa02ed814a'),
    sa.PrimaryKeyConstraint('id', name='PK_8dce90771b71ea68844139af60b')
    )
    op.create_table('follow',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('follower_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('followed_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='FK_952d77375f7e56e7037893744d1'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='FK_e65ef3268d3d5589f94b09c2373'),
    sa.PrimaryKeyConstraint('id', name='PK_fda88bc28a84d2d6d06e19df6e5')
    )
    op.create_table('rock_climb',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('route_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('route_id', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('boulder', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sport', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('trad', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('top_rope', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sector_id', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('area_code', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('safety', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('rating_mean', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('rating_count', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_5af9c07930ecd8c87c93115772e')
    )
    op.create_table('authorization_role',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_04d137cc39f56d87683890e9fd5'),
    postgresql_ignore_search_path=False
    )
    op.create_table('shared_list_item',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('shared_list_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='FK_00130026f2d79264c2855d073b5'),
    sa.ForeignKeyConstraint(['shared_list_id'], ['shared_list.id'], name='FK_a1e51651134285c5a273a15ff42'),
    sa.PrimaryKeyConstraint('id', name='PK_9d9b9d766238793bc85e4f96b20')
    )
    op.create_table('baseline',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('baseline', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_valid', sa.VARCHAR(), server_default=sa.text("'VALID'::character varying"), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_fc0cfa4045a2e94623370763941'),
    sa.PrimaryKeyConstraint('id', name='PK_980ffba177cccda0ce36746ffa9')
    )
    op.create_table('goal',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_0833c5f34d131cf9a7af51f30cf'),
    sa.PrimaryKeyConstraint('id', name='PK_88c8e2b461b711336c836b1e130')
    )
    op.create_table('completed_activity',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='FK_af099b1014c6820d65bdd6ea55a'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_bca1c64bae66d9ee57d12bea28b'),
    sa.PrimaryKeyConstraint('id', name='PK_5a6172476ef4475638b63fe6933')
    )
    op.create_table('garmin_user_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('permissions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_6307370b67b4651d3363ca06fed')
    )
    op.create_table('activity',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('route_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('route_id', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('boulder', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sport', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('trad', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('top_rope', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sector_id', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('safety', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('mean', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('count', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('date_deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_24625a1d6b1b089c8ae206fe467')
    )
    op.create_table('authorization_role_user',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['authorization_role.id'], name='FK_f0ef14a8b6f3eeb474b4262c8c5'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK_2a9dafc66f034e6989132ddca82'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='PK_7af4cd62f5051ec064155aa25b2')
    )
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_category'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

