"""add_cards_table

Revision ID: 1d831e460f9a
Revises: f2990ed00faa
Create Date: 2025-11-15 12:53:46.304986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d831e460f9a'
down_revision = 'f2990ed00faa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if enum type exists, create if not
    bind = op.get_bind()
    result = bind.execute(sa.text("SELECT EXISTS(SELECT 1 FROM pg_type WHERE typname = 'cardtype')"))
    enum_exists = result.scalar()
    
    if not enum_exists:
        bind.execute(sa.text("CREATE TYPE cardtype AS ENUM ('debit', 'credit')"))
        bind.commit()
    
    # Create table using raw SQL to avoid enum creation issues
    bind.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS cards (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NOT NULL,
            card_number VARCHAR NOT NULL,
            cardholder_name VARCHAR NOT NULL,
            expiry_date DATE NOT NULL,
            card_type cardtype NOT NULL,
            bank_name VARCHAR,
            is_default BOOLEAN NOT NULL DEFAULT false,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            CONSTRAINT fk_cards_user_id FOREIGN KEY (user_id) REFERENCES users(id)
        )
    """))
    
    # Create indexes
    bind.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_cards_id ON cards(id)"))
    bind.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_cards_user_id ON cards(user_id)"))
    bind.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_user_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_table('cards')
    # Drop enum type
    sa.Enum(name='cardtype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

