"""fix_missing_indexes_and_vendor_constraints

Revision ID: 272f9afcdb98
Revises: 7a8b9c0d1e2f
Create Date: 2025-11-15 20:16:27.940656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272f9afcdb98'
down_revision = '7a8b9c0d1e2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    # Create indexes if they don't exist (idempotent)
    bind.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_payments_vendor_id ON payments(vendor_id)"))
    bind.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_users_reset_token ON users(reset_token)"))

    # Fix vendor table columns (these are minor type differences, safe to skip if already correct)
    try:
        op.alter_column('vendors', 'hours',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
    except Exception:
        pass

    try:
        op.alter_column('vendors', 'accepts_meal_plan',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   existing_server_default=sa.text('true'))
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'accepts_meal_plan',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('vendors', 'hours',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_payments_vendor_id'), table_name='payments')
    # ### end Alembic commands ###

