"""add_wallets_table

Revision ID: fd52396f852f
Revises: 1d831e460f9a
Create Date: 2025-11-15 15:48:24.859439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd52396f852f'
down_revision = '1d831e460f9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    
    # Create wallets table using raw SQL
    bind.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS wallets (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NOT NULL UNIQUE,
            balance DOUBLE PRECISION NOT NULL DEFAULT 0.0,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            CONSTRAINT fk_wallets_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
    """))
    
    # Create indexes
    bind.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_wallets_id ON wallets(id)"))
    bind.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_wallets_user_id ON wallets(user_id)"))
    bind.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###

